- name: Reset Cluster
  command: kubeadm reset --force

- name: Cleanup
  shell: |
          systemctl stop kubelet
          systemctl stop docker
          rm -rf /var/lib/cni/
          rm -rf /var/lib/kubelet/*
          rm -rf /etc/cni/
          ifconfig cni0 down
          ifconfig flannel.1 down
          ifconfig docker0 down
          ip link set cni0 down
          brctl delbr cni0
          systemctl restart kubelet
          systemctl restart docker

- name: Copy the join command to server location
  copy: src=join-command dest=/tmp/join-command.sh mode=0777

- name: Join the node to cluster
  command: sh /tmp/join-command.sh
