- name: Reset Cluster
  command: kubeadm reset --force

- name: Initialize Kubernetes Cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{host_ip}}

- name: Mkdir .kube
  ansible.builtin.file:
    path: .kube
    state: directory

- name: Copy config
  copy:
    src: /etc/kubernetes/admin.conf 
    dest: .kube/config
    remote_src: yes

- name: Change kubeconfig file permission
  file:
    path: .kube/config 
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Register interface as a variable
  shell: ip -o a show | grep "{{host_ip}}" | cut -d ' ' -f 2
  register: command_output

- set_fact:
      interface={{command_output.stdout}}

- name: Copy yamls dir to VM2
  ansible.builtin.copy:
    src: "yamls/{{ item }}"
    dest: ./
  with_items:
    - kube-flannel.yaml
    - postgres-deployment.yaml
    - postgres-pv.yaml
    - wiki-deployment.yaml

- name: Remove line in kube-scheduler
  ansible.builtin.lineinfile:
    path: /etc/kubernetes/manifests/kube-scheduler.yaml
    regexp: '- --port=0'
    state: absent

- name: Deploy the Flannel Network replace file
  ansible.builtin.replace:
    path: kube-flannel.yaml
    regexp: '- --iface=.+\n'
    replace: '- --iface={{ interface }}\n'

- name: Deploy the Flannel Network
  become: no
  command: kubectl apply -f kube-flannel.yaml

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"